### ISSUE TITLE
Inquiry about open-sourcing training code

### ISSUE THREAD

**Issue by XavierHeart** [naver-ai/prolip#1]
Hi, I'd like to express my sincere appreciation for this excellent work. I've been following its progress with great interest, particularly the training aspects. Could you kindly provide any information about when the training code might be open-sourced?I'm looking forward to the future developments of this project!!!

**Comment by SanghyukChun** [comment]
Hi, it might take some time because I now handle multiple projects.
I would like to expect that the training code will be cleaned up around Dec ~ Jan, but not confident.

You can easily implement the training code by editing open clip 2.24.0 using ProLIP main modules that are already public in the `prolip` directory
- https://github.com/mlfoundations/open_clip/tree/v2.24.0
- https://github.com/naver-ai/prolip/tree/main/src/prolip

**Comment by XavierHeart** [comment]
The estimated timeline for the training code cleanup is very helpful. I'm also grateful for the suggestions! Thanks~

**Comment by SanghyukChun** [comment]
@XavierHeart Hi, the training code has been released. It will not work as-is (e.g., you need training datasets), but it will be a good starting point if you are still interested in.
